### ISSUE TITLE
Avo Inspector adds unwanted permission to production

### ISSUE THREAD

**Issue by pedronveloso** [avohq/android-avo-inspector#16]
When adding Avo Inspector to our project I've noticed it adds an unwanted permission:

`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />`

Please note the below screenshot as well:

<img width="1045" alt="Screen Shot 2020-11-02 at 1 09 05 PM" src="https://user-images.githubusercontent.com/416941/97920751-e94d0100-1d27-11eb-82e7-94ff12b12f28.png">

My instinct tells me that this permission is possibly there for the on screen event counter that the library provides for development. This suggests that both the permission and the Debug Activity that are added should really be part of a `debugImplementation` that could be consumed separately. We've have added specific rules to remove the permission from the Merged Manifest, but this is should be handled on Avo's side not on client's projects.

**Comment by alex-tpom6oh** [comment]
Hi @pedronveloso, we've just released [version 2.0.0](https://github.com/avohq/android-avo-inspector/releases/tag/2.0.0) that addresses this issue!
