### ISSUE TITLE
Avo inspector crashes app

### ISSUE THREAD

**Issue by kingsleyadio** [avohq/android-avo-inspector#24]
When adding Avo inspector to our project, it crashes our app

We realized that Avo uses **Sentry v 1.7.x** internally, while our app uses a much newer **v 5.6.1**. And because Gradle picks the newer version, some of the classes referenced by Avo (`ConfigurationProvider` in particular) ends up not being available at runtime causing a `NoClassDefFoundError`

Is there any chance that upgrading the version of Sentry is an option for you? Or could you perhaps wrap the whole Sentry initialization in a `catch(Throwable)` as a worst case scenario?

Thank you

**Comment by bragur** [comment]
Thanks @kingsleyadio we'll have a look!

**Comment by alex-tpom6oh** [comment]
Hey @kingsleyadio, please check the 2.0.3 release

**Comment by kingsleyadio** [comment]
Hey @alex-tpom6oh @bragur 

Seems to be fine now. Thanks for dealing with this very quickly 🚀
